variable "project" {}
variable "region" {}
variable "zone" {}
variable "credentials_file" {}
variable "new" {}
variable "machine_type" {}
variable "boot_disk_image"       {}
variable "boot_disk_size_gb"     {}
variable "boot_disk_type"        {}
variable "boot_disk_auto_delete" {}
